### ISSUE TITLE
Code is missing

### ISSUE THREAD

**Issue by mvkra** [rikace/FSSignalR#1]
Just found your example while looking for pointers on SignalR. Just wanted to point out to you that at time of writing the code for your project is missing (i.e I see the solution file but no source directories). Not sure if this is intentional or not.

**Comment by rikace** [comment]
Hi,

I am sorry for the inconvenient. I did some work few weeks ago and apparently I messed up.

I am fixing today and I will send you an email later.

Riccardo

**Comment by rikace** [comment]
I updated the code.

Let me know if you have problems

Riccardo

**Comment by mvkra** [comment]
Sorry still don't see the code on master.

**Comment by rikace** [comment]
Hi,

I have checked in the code and double check
here is the link

https://github.com/rikace/Presentations/tree/master/SignalRandFS

**Comment by mvkra** [comment]
Right I didn't realise the code was in a different plance (i.e under Presentations).
Will close this issue - thanks for the help! Maybe this repository should be deleted or at least alert the user that it has moved to the new location.
